spring:
  datasource:
    username: root
    password: atarashii
    url: jdbc:mysql://localhost:3306/ours?useUnicode=true&characterEncoding=utf-8
    driver-class-name:  com.mysql.cj.jdbc.Driver

#  thymeleaf:
#    mode: HTML
#    encoding: utf-8
#    cache: false
#    prefix: classpath:/templates/

